import '../globals.css'

export const metadata = {
  title: 'Abdulrahman Rihan',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-white">
      <main>{children}</main>
    </html>
  )
}
