import '../globals.css'
import Head from 'next/head';

export const metadata = {
  title: 'Abdulrahman Rihan',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-white">
      <Head>
        <link rel='shortcut icon' href='../favicon.png'/>
      </Head>
      <main>{children}</main>
    </html>
  )
}
