import '../globals.css'
import Link from "next/link"

export const metadata = {
  title: 'My Awesome Site',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-white">
      <main>{children}</main>
    </html>
  )
}
